library(Seurat)
library(future)
library(pbapply)
library(future.apply)
source("Seurat/seurat_code/utilities.R")
source("Seurat/seurat_code/clustering.R")
source("Seurat/seurat_code/convenience.R")
source("Seurat/seurat_code/data.R")
source("Seurat/seurat_code/dimensional_reduction.R")
source("Seurat/seurat_code/mixscape.R")
source("Seurat/seurat_code/objects.R")
source("Seurat/seurat_code/RcppExports.R")
source("Seurat/seurat_code/reexports.R")

seurat_obj <- readRDS('seurat_object.rds')
seurat_obj_2 <- readRDS('seurat_object_2.rds')
data.list <- SplitObject(seurat_obj)
data.list <- c(data.list, SplitObject(seurat_obj))
# for (i in 1:length(data.list)) {
#     data.list[[i]] <- NormalizeData(data.list[[i]])
#     data.list[[i]] <- ScaleData(data.list[[i]])
#     data.list[[i]] <- FindVariableFeatures(data.list[[i]])
# }
anchors <- FindIntegrationAnchors(object.list = data.list, anchor.features = 30)

source("Seurat/seurat_code/integration.R")
somrthing <- IntegrateData(anchors)